### PR TITLE
fix: upgrade python version to match django requirements

### PR DESCRIPTION
**Pull request by ArturBa**
upgraded python to fix the #26

### CODE REVIEW

**Comment by adriancast** [comment]
Hello @ArturBa!

Thanks for the contribution. Testing your PR I have the following error:
```
$ docker-compose build                                                          16 ↵
[+] Building 0.7s (5/5) FINISHED
 => [scrapyd-django-template-django internal] load build definition from Dockerfile                                                                          0.0s
 => => transferring dockerfile: 31B                                                                                                                          0.0s
 => [scrapyd-django-template-scrapyd internal] load build definition from Dockerfile                                                                         0.0s
 => => transferring dockerfile: 31B                                                                                                                          0.0s
 => [scrapyd-django-template-django internal] load .dockerignore                                                                                             0.0s
 => => transferring context: 2B                                                                                                                              0.0s
 => [scrapyd-django-template-scrapyd internal] load .dockerignore                                                                                            0.0s
 => => transferring context: 2B                                                                                                                              0.0s
 => ERROR [scrapyd-django-template-django internal] load metadata for docker.io/library/python:3.11.0-stretch                                                0.5s
------
 > [scrapyd-django-template-django internal] load metadata for docker.io/library/python:3.11.0-stretch:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/library/python:3.11.0-stretch: not found
```

Could you confirm that this PR is working in your machine ?

Thanks for the contribution 👍🏼

**Comment by adriancast** [comment]
Hey @ArturBa , If you use the following version it should work:
`FROM python:3.10`

Update your PR and I will accept it

**Comment by ArturBa** [comment]
updated

**Review by adriancast — APPROVED** [review]

**Comment by adriancast** [comment]
Thanks @ArturBa !

**Pull request merged**
